### ISSUE TITLE
Image upload should work with CSRF validation

### ISSUE THREAD

**Issue by alanwillms** [2amigos/yii2-ckeditor-widget#2]
On setting `filebrowserUploadUrl` CKEditor should submit `Yii::$app->request->csrfParam` and `Yii::$app->request->csrfToken` so that the form works with CSRF validation.

As far as I know, the only way to solve this is injecting a hidden input in the upload form:

``` js
function prepareCkEditor(containerId)
{
    if (jQuery('#' + containerId).length > 0) {

        jQuery(document).on('click', '.cke_dialog_tabs a:eq(2)', function(event) {

            var csrfTokenInput = jQuery('<input />');
            csrfTokenInput.attr('type', 'hidden');
            csrfTokenInput.attr('name', window.csrfVar);
            csrfTokenInput.val(window.csrfToken);

            jQuery('.cke_dialog_ui_input_file iframe').contents().find('form').append(csrfTokenInput);
        });
    }
}
```

**Comment by nirvana-msu** [comment]
This only works as long as our `Upload` tab is the third matched element, i.e. you only have a single widget on the page. It breaks if you have multiple widgets loaded or, as in my particular case, when you load the widget several times via ajax (e.g. when the user wants to edit the content). If several widgets are added without reloading the page, `eq(2)` matches the old `Upload` tab instead of the new one. 

The following modification seems to be generic enough to cover multiple widgets on the same page. Instead of `a:eq(2)` it uses `a[title="Upload"]` to match all `Upload` tabs. There would also be several forms (including old ones) on the page, so it iterates over them all to add a token if missing:

```
yii & $(document).off('click', '.cke_dialog_tabs a[title="Upload"]').on('click', '.cke_dialog_tabs a[title="Upload"]', function () {
    var $forms = $('.cke_dialog_ui_input_file iframe').contents().find('form');
    var csrfName = yii.getCsrfParam();
    $forms.each(function () {
        if (!$(this).find('input[name=' + csrfName + ']').length) {
            var csrfTokenInput = $('<input/>').attr({
                'type': 'hidden',
                'name': csrfName
            }).val(yii.getCsrfToken());
            $(this).append(csrfTokenInput);
        }
    });
});
```

**Comment by tonydspaniard** [comment]
@nirvana-msu do you mind providing a PR for that change? I would be more than happy to merge it (but please, make sure tests pass, I have been forced not to merge others due to that issue)

thanks!
