### ISSUE TITLE
Options >> Rows

### ISSUE THREAD

**Issue by osCMattiFinn** [2amigos/yii2-ckeditor-widget#39]
Setting 'options' => ['rows' => 12] does nothing.  There are still only the default 5 rows.

**Comment by amit4sky** [comment]
Please fix this issue or give any solution . we are disappointed due to this issue.

**Comment by osCMattiFinn** [comment]
This is ridiculous, no reply in this amount of time.

Not only do options not work, but it also does not follow the configuration attributes we find on the cKeditor website.

Further, I just initialized it inside a jQuery UI dialog and it floats above the dialog and completely disappears from the screen if I click anywhere on the page!

Time to move onto something worthwhile......

**Comment by osCMattiFinn** [comment]
Forget this piece of junk, here is one that works beautifully:

https://packagist.org/packages/himiklab/yii2-ckeditor-widget

**Comment by tonydspaniard** [comment]
Thank you for your kind comment @osCMattiFinn. Maybe is time for you to try to learn something too and don't put the pressure on others that give their time and work for free. No response because we have lots of work to handle, ***paying work***, and due that is paid it has top priority. Sorry for not taking your urgent requirements seriously.
