### ISSUE TITLE
Toolbar items Image , Link not working in Modal  

### ISSUE THREAD

**Issue by shahzadthathal** [2amigos/yii2-ckeditor-widget#75]
I have integrate my form in modal and then use this widget in modal form but when I click on Image or Link button in toolbar , it show a new popup but input fields are not getting any value, even I'm unable to click on those fields.

<?php Modal::begin([
    "id"=>"ajaxCrudModal",
    "footer"=>"",// always need it for jquery plugin
])?>
<?php Modal::end(); ?>

How should I solve this issue?

**Comment by WadeShuler** [comment]
I believe that this repo is dead. Maybe one day he will revive it.

Until then, please check out my repo: [https://github.com/WadeShuler/yii2-ckeditor-cdn](https://github.com/WadeShuler/yii2-ckeditor-cdn)

I am not sure what your issue is, and it seems like you are new to all of this (my hint: you didn't put your code in a code block). Maybe it is a javascript conflict between your site and his extension? Try mine, and see if you have better luck.

My version is a lot cleaner and future/update proof than this repo. I am hoping some of you can test it out, provide feedback, and it can become the go-to yii2 extension for using ckeditor.

**Comment by tonydspaniard** [comment]
@shahzadthathal  is it content ajaxed? if so, the problem is that the plugin needs to be re-initialized. If not, then make sure you have no CSS conflicts with the overlay.

**Comment by Resmedia** [comment]
Add this after your code and will be OK. I had same problem. 

`<script>
    $.fn.modal.Constructor.prototype.enforceFocus = function () {
        modal_this = this
        $(document).on('focusin.modal', function (e) {
            if (modal_this.$element[0] !== e.target && !modal_this.$element.has(e.target).length
                && !$(e.target.parentNode).hasClass('cke_dialog_ui_input_select')
                && !$(e.target.parentNode).hasClass('cke_dialog_ui_input_text')) {
                modal_this.$element.focus()
            }
        })
    };
</script>`

**Comment by shahzadthathal** [comment]
Thanks I will try.

**Comment by tonydspaniard** [comment]
Thank you @Resmedia for the sample. Very kind of you.
