### ISSUE TITLE
ExtraPlugins don't work

### ISSUE THREAD

**Issue by marciocamello** [2amigos/yii2-ckeditor-widget#9]
```php
$form->field($model, 'content')->textarea(['rows' => 6])->widget(CKEditor::className(),[
    		'preset' => 'full',
    		'clientOptions' => [
    			'allowedContent' => true,
    			'extraPlugins' => 'pluginName'
    		]
    	]) ;
```

This don't work, assets not render plugin.js

**Comment by tonydspaniard** [comment]
@marciocamello after revisiting the widget and refactoring issues I've found that the problem is that you need to have the plugin installed in the `plugins` folder. 

If you wish to add another plugin, you will have to create your own package with the plugins selected and then extend the AssetBundle of this extension to override the assets source. No other way, sorry.
